
LATEX_BASE_NAME = slides
LATEX_COMMAND = latex $(LATEX_BASE_NAME).tex;
#LATEX_COMMAND = latex $(LATEX_BASE_NAME).tex; bibtex $(LATEX_BASE_NAME)
#LATEX_COMMAND = latex $(LATEX_BASE_NAME).tex; makeindex $(LATEX_BASE_NAME).idx
#FIG := $(wildcard *.fig)
#EPS := $(FIG:.fig=.eps)

########################################
default : ps
########################################

ps : $(LATEX_BASE_NAME).ps
	ghostview $<

pdf : $(LATEX_BASE_NAME).pdf

%.pdf : %.ps
	ps2pdf $<

%.ps : %.dvi 
	dvips -o $@ $<

re :
	$(LATEX_COMMAND)
	$(LATEX_COMMAND)

$(LATEX_BASE_NAME).dvi : $(LATEX_BASE_NAME).tex
	$(LATEX_COMMAND)

tar : clean
	@cd ..; tar cfz beamer_`date +"%Y_%m_%d"`.tar.gz beamer
	@echo file  ../beamer_`date +"%Y_%m_%d"`.tar.gz created

#%.eps : %.fig
#	fig2dev -L eps $< $@

########################################
clean :
	rm -rf *~ $(LATEX_BASE_NAME).dvi $(LATEX_BASE_NAME).aux $(LATEX_BASE_NAME).log $(LATEX_BASE_NAME).ps *.bak $(LATEX_BASE_NAME).pdf $(LATEX_BASE_NAME).bbl $(LATEX_BASE_NAME).blg $(LATEX_BASE_NAME).toc $(LATEX_BASE_NAME).idx  $(LATEX_BASE_NAME).ilg  $(LATEX_BASE_NAME).ind $(LATEX_BASE_NAME).nav  $(LATEX_BASE_NAME).out  $(LATEX_BASE_NAME).snm


